version: "3"
services:
    jekyll:
        image: jekyll/jekyll:pages
        command: jekyll serve --force_polling --incremental
        container_name: "${PROJECT_NAME}_jekyll"
        ports:
            - 4000:4000
        volumes:
            - ./docs:/srv/jekyll
